steps:
# Build the container image
- name: 'gcr.io/cloud-builders/docker'
  args: ['build', '-t', 'gcr.io/$PROJECT_ID/conflux-three-body-backend', '.']

# Push the container image to Container Registry
- name: 'gcr.io/cloud-builders/docker'
  args: ['push', 'gcr.io/$PROJECT_ID/conflux-three-body-backend']

# Deploy container image to Cloud Run
- name: 'gcr.io/google.com/cloudsdktool/cloud-sdk'
  entrypoint: gcloud
  args:
  - 'run'
  - 'deploy'
  - 'conflux-three-body-backend'
  - '--image'
  - 'gcr.io/$PROJECT_ID/conflux-three-body-backend'
  - '--platform'
  - 'managed'
  - '--region'
  - 'us-east1'
  - '--allow-unauthenticated'

images:
- 'gcr.io/$PROJECT_ID/conflux-three-body-backend'